# Generated by Django 4.2.8 on 2023-12-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('Sci-fi', 'Science Fiction'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Musical', 'Musical'), ('Mystery', 'Mystery')], max_length=50, verbose_name='Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('poster', models.CharField(max_length=500, null=True, verbose_name='Poster')),
                ('summary', models.TextField(max_length=500, null=True, verbose_name='Summary')),
                ('trailer', models.CharField(max_length=100, null=True, verbose_name='Trailer Link')),
                ('download', models.CharField(max_length=100, null=True, verbose_name='Download Link')),
                ('rating', models.PositiveIntegerField(null=True, verbose_name='Rating')),
                ('release_date', models.DateField(null=True, verbose_name='Release Date')),
                ('trending', models.PositiveIntegerField(null=True, verbose_name='Trending')),
                ('language', models.CharField(max_length=100, null=True, verbose_name='Language')),
                ('industry', models.CharField(choices=[('Hollywood', 'Hollywood'), ('Nollywood', 'Nollywood')], max_length=50, null=True, verbose_name='Industry')),
                ('runtime', models.CharField(max_length=50, null=True, verbose_name='Runtime')),
                ('company', models.CharField(max_length=50, null=True, verbose_name='Company')),
                ('star_rating', models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=50, null=True, verbose_name='Star rating')),
            ],
        ),
        migrations.CreateModel(
            name='TvSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('poster', models.CharField(max_length=500, null=True, verbose_name='Poster')),
                ('summary', models.TextField(max_length=500, null=True, verbose_name='Summary')),
                ('language', models.CharField(max_length=100, null=True, verbose_name='Language')),
                ('release_date', models.DateField(null=True, verbose_name='Release Date')),
                ('company', models.CharField(max_length=50, null=True, verbose_name='Company')),
                ('industry', models.CharField(choices=[('Hollywood', 'Hollywood'), ('Nollywood', 'Nollywood')], max_length=50, null=True, verbose_name='Industry')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TvSeriesCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof_box.artist')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof_box.tvserie')),
            ],
        ),
        migrations.AddField(
            model_name='tvserie',
            name='cast',
            field=models.ManyToManyField(related_name='series', through='jollof_box.TvSeriesCast', to='jollof_box.artist'),
        ),
        migrations.AddField(
            model_name='tvserie',
            name='genres',
            field=models.ManyToManyField(to='jollof_box.genre'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField(null=True, verbose_name='Season')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof_box.tvserie')),
            ],
            options={
                'ordering': ['series', 'season'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof_box.artist')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jollof_box.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(related_name='movie', through='jollof_box.MovieCast', to='jollof_box.artist'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='jollof_box.genre'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.PositiveIntegerField(null=True, verbose_name='Episode')),
                ('download', models.CharField(max_length=100, null=True, verbose_name='Download Link')),
                ('rating', models.PositiveIntegerField(null=True, verbose_name='Rating')),
                ('star_rating', models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=50, null=True, verbose_name='Star rating')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jollof_box.season')),
            ],
            options={
                'ordering': ['season', 'episode'],
            },
        ),
    ]
