# Generated by Django 4.2.8 on 2023-12-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='star_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star_rating',
        ),
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=50, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('action', 'action'), ('horror', 'horror'), ('drama', 'drama'), ('thriller', 'thriller'), ('comedy', 'comedy'), ('sci-fi', 'sci-fi'), ('romance', 'romance'), ('adventure', 'adventure'), ('fantasy', 'fantasy'), ('animation', 'animation'), ('musical', 'musical'), ('mystery', 'mystery')], max_length=50, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='industry',
            field=models.CharField(choices=[('hollywood', 'hollywood'), ('nollywood', 'nollywood'), ('bollywood', 'bollywood')], max_length=50, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=50, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='tvserie',
            name='industry',
            field=models.CharField(choices=[('hollywood', 'hollywood'), ('nollywood', 'nollywood'), ('bollywood', 'bollywood')], max_length=50, null=True, verbose_name='Industry'),
        ),
    ]
