# Generated by Django 4.2.8 on 2023-12-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0002_remove_episode_star_rating_remove_movie_star_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=1000, null=True, verbose_name='Poster'),
        ),
    ]
