# Generated by Django 4.2.8 on 2023-12-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0003_alter_movie_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecast',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='moviecast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tvseriescast',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='tvseriescast',
            name='series',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='casts',
        ),
        migrations.RemoveField(
            model_name='tvserie',
            name='cast',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='MovieCast',
        ),
        migrations.DeleteModel(
            name='TvSeriesCast',
        ),
    ]
