# Generated by Django 4.2.8 on 2023-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0004_remove_moviecast_artist_remove_moviecast_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film',
            field=models.CharField(default='movie', max_length=10, verbose_name='Film'),
        ),
        migrations.AddField(
            model_name='tvserie',
            name='film',
            field=models.CharField(default='series', max_length=10, verbose_name='Film'),
        ),
    ]
