# Generated by Django 4.2.8 on 2023-12-09 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0005_movie_film_tvserie_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Rating'),
        ),
    ]
