# Generated by Django 4.1.6 on 2023-11-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='Download_link',
            new_name='download',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='Trending',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
    ]
