# Generated by Django 4.1.6 on 2023-11-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0003_rename_genre_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(max_length=500, null=True, verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='tvserie',
            name='poster',
            field=models.CharField(max_length=500, null=True, verbose_name='Poster'),
        ),
    ]
