# Generated by Django 4.2.8 on 2023-12-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0004_alter_movie_poster_alter_tvserie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Summary',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=100, null=True, verbose_name='Language'),
        ),
    ]
