# Generated by Django 4.2.8 on 2023-12-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0005_rename_summary_movie_summary_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Horror', 'Horror'), ('Drama', 'Drama'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('Sci-fi', 'Science Fiction'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Musical', 'Musical'), ('Mystery', 'Mystery')], max_length=50, verbose_name='Genre'),
        ),
    ]
