# Generated by Django 4.2.8 on 2023-12-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0006_alter_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvserie',
            name='language',
            field=models.CharField(max_length=100, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='tvserie',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Release Date'),
        ),
    ]
