# Generated by Django 4.2.8 on 2023-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0007_tvserie_language_tvserie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.CharField(max_length=50, null=True, verbose_name='Runtime'),
        ),
    ]
