# Generated by Django 4.2.8 on 2023-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0008_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='company',
            field=models.CharField(max_length=50, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='tvserie',
            name='company',
            field=models.CharField(max_length=50, null=True, verbose_name='Company'),
        ),
    ]
