# Generated by Django 4.2.8 on 2023-12-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0009_movie_company_tvserie_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star_rating',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐', '⭐')], max_length=50, null=True, verbose_name='Star rating'),
        ),
    ]
