# Generated by Django 4.2.8 on 2023-12-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jollof_box', '0015_alter_movie_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='star_rating',
            field=models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=50, null=True, verbose_name='Star rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star_rating',
            field=models.CharField(choices=[('⭐', 1), ('⭐⭐', 2), ('⭐⭐⭐', 3), ('⭐⭐⭐⭐', 4), ('⭐⭐⭐⭐⭐', 5)], max_length=50, null=True, verbose_name='Star rating'),
        ),
    ]
